spring:
  application:
    name: techtest-imran
  datasource:
    url: jdbc:h2:mem:myh2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  servlet:
    context-path: /techtest-imran
